// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enabled": boolean;
      "autoProcessNewItems": boolean;
      "defaultTitleMode": string;
      "defaultPublicationMode": string;
      "defaultPublisherMode": string;
      "defaultCreatorMode": string;
      "processTitles": boolean;
      "processPublications": boolean;
      "processPublishers": boolean;
      "processPlaces": boolean;
      "processCreators": boolean;
      "processIdentifiers": boolean;
      "previewBeforeApply": boolean;
      "addTagAfterProcessing": string;
      "skipTag": string;
      "exceptionWords": string;
    };
  }
}
